module Bga
  BGA_GAMES = [
    "6 nimmt!",
    "7 Wonders Duel",
    "7 Wonders",
    "Abyss",
    "Alhambra",
    "Cacao",
    "Can't Stop",
    "Carcassonne",
    "Carcassonne: Hunters and Gatherers",
    "Caylus",
    "Celestia",
    "Chess",
    "City of the Big Shoulders",
    "Clans of Caledonia",
    "Coloretto",
    "Colt Express",
    "Concept",
    "Coup",
    "Cribbage",
    "Dice Forge",
    "Downforce",
    "Draftosaurus",
    "Dragon Castle",
    "Dungeon Petz",
    "Eminent Domain",
    "Fleet",
    "For Sale",
    "Forbidden Island",
    "Go",
    "Haggis",
    "Hanabi",
    "Hawaii",
    "Hive",
    "In The Year of the Dragon",
    "Diamant",
    "Innovation",
    "Jaipur",
    "K2",
    "Keyflower",
    "Kingdom Builder",
    "Kingdomino",
    "La Granja",
    "Lewis & Clark: The Expedition ",
    "Libertalia",
    "Lords of Xidit",
    "Lost Cities",
    "Love Letter",
    "Luxor",
    "Madeira",
    "Marco Polo II: In the Service of the Khan",
    "Mr. Jack",
    "Nippon",
    "No Thanks!",
    "Not Alone",
    "Perudo",
    "Polis: Fight for the Hegemony",
    "Potion Explosion",
    "Puerto Rico",
    "Quantum",
    "Quarto",
    "Race for the Galaxy",
    "Red7",
    "Res Arcana",
    "Roll for the Galaxy",
    "Russian Railroads",
    "Saint Petersburg",
    "Santorini",
    "Seasons",
    "Signorie",
    "Spyrium",
    "Stone Age",
    "Sushi Go!",
    "Takenoko",
    "Taluva",
    "Targi",
    "Tash-Kalar: Arena of Legends",
    "Teotihuacan: City of Gods",
    "Terra Mystica",
    "The Crew: The Quest for Planet Nine",
    "The Palaces of Carrara",
    "The Voyages of Marco Polo",
    "Through the Ages: A New Story of Civilization",
    "Through the Ages: A Story of Civilization",
    "Thurn and Taxis",
    "Tobago",
    "Tokaido",
    "Troyes",
    "Tzolk'in: The Mayan Calendar",
    "Welcome To...",
    "Yokohama",
  ]
end
