module Bga
  BGA_GAMES = [
    "6 nimmt!",
    "7 Wonders Duel",
    "7 Wonders",
    "Abyss",
    "Alhambra",
    "Cacao",
    "Can't Stop",
    "Carcassonne",
    "Carcassonne: Hunters and Gatherers",
    "Caylus",
    "Celestia",
    "Chess",
    "City of the Big Shoulders",
    "Clans of Caledonia",
    "Coloretto",
    "Colt Express",
    "Concept",
    "Coup",
    "Cribbage",
    "Dice Forge",
    "Downforce",
    "Draftosaurus",
    "Dragon Castle",
    "Dungeon Petz",
    "Eminent Domain",
    "Fleet",
    "For Sale",
    "Forbidden Island",
    "Go",
    "Haggis",
    "Hanabi",
    "Hawaii",
    "Hive",
    "In The Year of the Dragon",
    "Diamant",
    "Innovation",
    "Jaipur",
    "K2",
    "Keyflower",
    "Kingdom Builder",
    "Kingdomino",
    "La Granja",
    "Lewis & Clark: The Expedition ",
    "Libertalia",
    "Lords of Xidit",
    "Lost Cities",
    "Love Letter",
    "Luxor",
    "Madeira",
    "Marco Polo II: In the Service of the Khan",
    "Mr. Jack",
    "Nippon",
    "No Thanks!",
    "Not Alone",
    "Perudo",
    "Polis: Fight for the Hegemony",
    "Potion Explosion",
    "Puerto Rico",
    "Quantum",
    "Quarto",
    "Race for the Galaxy",
    "Red7",
    "Res Arcana",
    "Roll for the Galaxy",
    "Russian Railroads",
    "Saint Petersburg",
    "Santorini",
    "Seasons",
    "Signorie",
    "Spyrium",
    "Stone Age",
    "Sushi Go!",
    "Takenoko",
    "Taluva",
    "Targi",
    "Tash-Kalar: Arena of Legends",
    "Teotihuacan: City of Gods",
    "Terra Mystica",
    "The Crew: The Quest for Planet Nine",
    "The Palaces of Carrara",
    "The Voyages of Marco Polo",
    "Through the Ages: A New Story of Civilization",
    "Through the Ages: A Story of Civilization",
    "Thurn and Taxis",
    "Tobago",
    "Tokaido",
    "Troyes",
    "Tzolk'in: The Mayan Calendar",
    "Welcome To...",
    "Yokohama",
  ]

  YUCATA_GAMES = [
    "7 Steps",
    "A Few Acres of Snow",
    "Alchemist",
    "Antike Duellum",
    "Argo",
    "Arkadia",
    "Arktia",
    "Aronda",
    "At the Gates of Loyang",
    "Atacama",
    "Atlantida",
    "Atoll",
    "Atta Ants",
    "Attika",
    "Automobiles",
    "Awale",
    "Balloon Cup",
    "Bangkok Klongs",
    "Black Friday",
    "Bruges",
    "Cacao",
    "Call To Glory",
    "Campaign Manager 2008",
    "Capt'n W. Kidd",
    "Carcassonne H&G",
    "Carcassonne South Seas",
    "Carolus Magnus",
    "Carpe Diem",
    "Carson City",
    "Carson City Cards",
    "Castle Rampage",
    "Chakra",
    "Chinagold",
    "City Blocks",
    "Claim It",
    "ConHex",
    "Down Under",
    "Dragonheart",
    "Drako",
    "Egizia",
    "El Grande",
    "Era of Inventions",
    "Famiglia",
    "Fantasy Dice Battles",
    "Fearsome Floors",
    "Finca",
    "Firenze",
    "First Class",
    "Forum Trajanum",
    "Founding Fathers",
    "Four in a row",
    "Glen More",
    "Gobang & Gomoku",
    "Grand Austria Hotel",
    "Ground Floor",
    "Guildhall",
    "Hacienda",
    "Hadara",
    "Hawaii",
    "Helios",
    "Hellas",
    "Hexxagon",
    "Hey, that's my fish",
    "Hunters and Scouts",
    "Imhotep",
    "Imhotep-Duel",
    "Industrial Waste",
    "Just 4 Fun",
    "Just 4 Fun Colours",
    "Kahuna",
    "Kamisado",
    "Kanaloa",
    "Kashgar",
    "Key HarvestBETA",
    "King of Siam",
    "La Granja",
    "La Granja No Siesta",
    "La Isla",
    "Las Vegas",
    "Lemminge",
    "Lift Off",
    "Lords of War",
    "Lorenzo",
    "Luna",
    "Macao",
    "Machi Koro",
    "Maori",
    "Masons",
    "Morris",
    "Mount Drago",
    "Mystic Vale",
    "Nations: The Dice Game",
    "Nauticus",
    "Navegador",
    "One-Eye",
    "Oracle of Delphi",
    "Oregon",
    "Othello",
    "Packet Row",
    "Pandoria",
    "Pax Porfiriana",
    "Pergamon",
    "Polis",
    "Pompeii",
    "Ponte del Diavolo",
    "Port Royal",
    "Puerto Rico (Cards)",
    "QANGO",
    "R-Eco",
    "Race",
    "Rajas of the Ganges",
    "RajasDice",
    "Rapa Nui",
    "Rattus",
    "Red7",
    "Richelieu",
    "Roll through the Ages",
    "Rose King",
    "Russian Railroads",
    "Saint Petersburg",
    "Santa Cruz",
    "Santiago de Cuba",
    "Schweinebande",
    "Sekigahara",
    "Shanghaien",
    "Six",
    "Skyline",
    "Snowdonia",
    "Sobek",
    "Space Mission",
    "Spexxx",
    "Steamrollers",
    "Sticky Fingers",
    "Stone Age",
    "Storm",
    "Sudoku Moyo",
    "Tally Ho!",
    "Targi",
    "Terra Mystica",
    "The Castles of Burgundy",
    "The Castles of Burgundy (Cards)",
    "The Great City of Rome",
    "The Hanging Gardens",
    "The Palaces of Carrara",
    "The Speicherstadt",
    "The Voyages of Marco Polo",
    "Thunderstone",
    "Thurn and Taxis",
    "To Court the King",
    "Torres",
    "Transatlantic",
    "Trias",
    "Twin Tin Bots",
    "Two by Two",
    "Tyrus",
    "Ulm",
    "Underwater Cities",
    "VOLT",
    "Valletta",
    "Vikings",
    "Vinci",
    "Völuspá",
    "War Chest",
    "Way of the Dragon",
    "Yspahan",
    "Yucata",
    "Zooloretto the dice game",
  ]
end
