class OnlineGames
  ONLINE_GAMES = [
    "6 nimmt!",
    "7 Wonders",
    "7 Wonders (Second Edition)",
    "7 Wonders: Architects",
    "After Us",
    "Akropolis",
    "Alhambra",
    "Applejack",
    "Azul",
    "Backgammon",
    "Bandido",
    "Break the Code",
    "Burgle Bros.",
    "Can't Stop",
    "Canvas",
    "Carcassonne",
    "Cartographers",
    "Century: Spice Road",
    "Challengers!",
    "Conspiracy: Abyss Universe",
    "CuBirds",
    "Decrypto",
    "Dice Forge",
    "Dog Park",
    "Draftosaurus",
    "Earth",
    "Evergreen",
    "For Sale",
    "Gin Rummy",
    "Hardback",
    "Hens",
    "Incan Gold",
    "It's a Wonderful World",
    "Jaipur",
    "Jump Drive",
    "Just One",
    "Kingdom Builder",
    "Kingdomino",
    "Lost Cities",
    "Love Letter",
    "Lucky Numbers",
    "Mandala",
    "Martian Dice",
    "Mini Rogue",
    "My City: Roll & Build",
    "My First Carcassonne",
    "New York Zoo",
    "Next Station: London",
    "Next Station: Tokyo",
    "Pandemic",
    "Patchwork",
    "Piraten Kapern",
    "Potion Explosion",
    "Puerto Rico",
    "Railroad Ink Challenge: Lush Green Edition",
    "Railroad Ink: Blazing Red Edition",
    "Railroad Ink: Deep Blue Edition",
    "Rallyman: GT",
    "Regicide",
    "Saboteur",
    "Sagani",
    "Shifting Stones",
    "Similo",
    "Skull",
    "Space Base",
    "SpellBook",
    "Splendor",
    "Spots",
    "Stella: Dixit Universe",
    "Super Mega Lucky Box",
    "Sushi Go Party!",
    "Sushi Go!",
    "Tapestry",
    "Targi",
    "The Crew: Mission Deep Sea",
    "The Crew: The Quest for Planet Nine",
    "The Isle of Cats",
    "Trailblazers",
    "Tranquility",
    "Trek 12",
    "Troyes Dice",
    "Turing Machine",
    "Via Magica",
    "Viticulture",
    "Viticulture Essential Edition",
    "Welcome To...",
    "Welcome To...: Collector's Edition",
    "Wingspan",
    "Wizard",
  ]

  def self.include?(game)
    ONLINE_GAMES.include?(game.name)
  end
end
