class PlayedGames
  PLAYED_GAMES = [
    "6 nimmt!",
    "7 Wonders (Second Edition)",
    "7 Wonders",
    "7 Wonders: Architects",
    "A Fake Artist Goes to New York",
    "A Feast for Odin",
    "Aeon's End",
    "After the Virus",
    "Agricola",
    "Alhambra",
    "Arboretum",
    "Ark Nova",
    "Arkham Horror: The Card Game",
    "Arkham Horror: The Card Game (Revised Edition)",
    "Ascension: Deckbuilding Game",
    "Awkward Guests: The Walton Case",
    "Azul",
    "BANG!",
    "Battle Line",
    "Blokus",
    "Bohnanza",
    "Brass: Birmingham",
    "Brass: Lancashire",
    "Bullet♥︎",
    "Calico",
    "Camel Up",
    "Camel Up (Second Edition)",
    "Can't Stop",
    "Carcassonne",
    "Cascadia",
    "Cat in the Box: Deluxe Edition",
    "CATAN",
    "Century: Golem Edition",
    "Century: Spice Road",
    "Chronicles of Avel",
    "Citadels",
    "Clank!: A Deck-Building Adventure",
    "Coconuts",
    "Codenames",
    "Coloretto",
    "Concordia",
    "DC Deck-Building Game",
    "Decrypto",
    "Deep Sea Adventure",
    "Dixit",
    "Dominion",
    "Dominion (Second Edition)",
    "Dorfromantik: The Board Game",
    "Draftosaurus",
    "Dragomino",
    "Elder Sign",
    "Ethnos",
    "Fabled Fruit",
    "Five Tribes: The Djinns of Naqala",
    "For Sale",
    "Forbidden Desert",
    "Friday",
    "Furnace",
    "Gloomhaven",
    "Gloomhaven: Jaws of the Lion",
    "Hanamikoji",
    "Harry Potter: Hogwarts Battle",
    "Herbaceous",
    "Hero Realms",
    "High Society",
    "Hive",
    "Incan Gold",
    "It's a Wonderful World",
    "Jaipur",
    "Jamaica",
    "Just One",
    "Karak",
    "Karuba",
    "King of Tokyo",
    "Kingdom Builder",
    "Kingdomino",
    "KLASK",
    "Las Vegas",
    "Legendary: A Marvel Deck Building Game",
    "Lords of Waterdeep",
    "Lost Cities",
    "Love Letter",
    "Machi Koro",
    "Marvel Champions: The Card Game",
    "Marvel United",
    "Marvel United: X-Men",
    "Meadow",
    "MicroMacro: Crime City",
    "Mists over Carcassonne",
    "MLEM: Space Agency",
    "Monopoly Deal Card Game",
    "My First Carcassonne",
    "My Lil' Everdell",
    "Mystic Vale",
    "New York Zoo",
    "NMBR 9",
    "No Thanks!",
    "Oh My Goods!",
    "Onirim",
    "Onirim (Second Edition)",
    "Onitama",
    "Orléans",
    "Outfoxed!",
    "Paleo",
    "Pandemic",
    "Patchwork",
    "Point Salad",
    "Port Royal",
    "Potion Explosion",
    "Puerto Rico",
    "Quarto",
    "Quoridor",
    "Qwirkle",
    "Qwixx",
    "Ra",
    "Race for the Galaxy",
    "Raiders of the North Sea",
    "Railroad Ink: Deep Blue Edition",
    "Reef",
    "Rhino Hero",
    "Roll For It!",
    "Roll for the Galaxy",
    "Roll Player",
    "Saboteur",
    "Sagrada",
    "Sail",
    "Saint Petersburg",
    "Santorini",
    "Schotten Totten",
    "SCOUT",
    "Sequence",
    "SET",
    "Sheriff of Nottingham",
    "Skull",
    "Sky Team",
    "Sleeping Gods",
    "Small World",
    "Space Base",
    "Splendor",
    "Spot it!",
    "Star Realms",
    "Star Realms: Frontiers",
    "Stone Age",
    "Sushi Go Party!",
    "Sushi Go!",
    "Take",
    "Takenoko",
    "Targi",
    "Terraforming Mars: Ares Expedition",
    "The Adventures of Robin Hood",
    "The Castles of Burgundy",
    "The Crew: Mission Deep Sea",
    "The Crew: The Quest for Planet Nine",
    "The Game",
    "The Grizzled",
    "The Initiative",
    "The Isle of Cats",
    "The LOOP",
    "The Lord of the Rings: The Card Game",
    "The Lord of the Rings: The Card Game – Revised Core Set",
    "The Lost Expedition",
    "The Mind",
    "The Quacks of Quedlinburg",
    "The Voyages of Marco Polo",
    "This War of Mine: The Board Game",
    "Ticket to Ride",
    "Tiny Epic Galaxies",
    "Tiny Towns",
    "Tokaido",
    "Tsuro",
    "Turing Machine",
    "Wavelength",
    "Welcome To...",
    "Wingspan",
    "Zombicide:",
    "Zombie Dice",
    "Zombie Kidz Evolution",
    "Zombie Teenz Evolution",

  ]

  def self.include?(game)
    PLAYED_GAMES.include?(game.name)
  end
end
